name: work-1
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: prod-env
      cancel-in-progress: false
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: prod-env
      cancel-in-progress: false
    environment: production
    steps:
      - name: Run a one-line script
        run: deploying ....
